### PR TITLE
avoid create root files when running tests

### PR DESCRIPTION
**Pull request by fblackburn1**

### CODE REVIEW

**Comment by sileht** [comment]
Does it fix an issue you have ? Or it's just to keep the local repository clean ?

**Comment by sileht** [comment]
Personally uses the cache a lot via --last-failed (except for this project because we can pass args).

I do `tox -e integration`, some tests fails, then I loop on:
 * run `tox -e integration -- -x --lf'
 * fix the failing tests

When no tests remain, Irerun the whole tests suite, one last times.

**Comment by fblackburn1** [comment]
Yes it fix jenkins fail https://jenkins.wazo.community/job/integration-tests-nolock/10593/console
For other project I agree, but since this project is a little bit arkward (test runner in a docker), then the modification should be only for this one.
If you use the cache in the docker, we can also use `-o cache_dir=/tmp` to avoid the problem

**Comment by sileht** [comment]
recheck

**Pull request merged**
